# TOML file for fpm as described at https://github.com/fortran-lang/fpm/blob/master/manifest-reference.md
name = "M_ncurses"
version = "0.1.0"
license = "MIT"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "Copyright 2021, John S. Urban"
description = "Fortran interface to ncurses(3c)"
categories = ["strings"]
keywords = ["fortran", "strings"]
homepage = "https://github.com/urbanjost/M_strings.git"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

link = "ncurses"

[install]
library = false

